
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'Nexys4UserDemo.ucf'
####################################################################################

#Nexys4 User Demo User Constraint File
# System Clock, 100MHz
set_property PACKAGE_PIN E3 [get_ports clk_i]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'clk_i' has been applied to the port object 'clk_i'.
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
#
#
#
##Buttons
##Bank = 15, Pin name = IO_L3P_T0_DQS_AD1P_15,		Sch name = CPU_RESET
set_property PACKAGE_PIN C12 [get_ports reset_i]				
	set_property IOSTANDARD LVCMOS33 [get_ports reset_i]
#
#	
##Bank = 15, Pin name = IO_L11N_T1_SRCC_15,	        Sch name = BTNC
set_property PACKAGE_PIN E16 [get_ports go_i]						
set_property IOSTANDARD LVCMOS33 [get_ports go_i]
#
#
# VGA Signals
set_property PACKAGE_PIN A3 [get_ports {vga_red_o[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_red_o[0]' has been applied to the port object 'vga_red_o[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_o[0]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_red_o[0]' has been applied to the port object 'vga_red_o[0]'.
set_property SLEW FAST [get_ports {vga_red_o[0]}]
set_property PACKAGE_PIN B4 [get_ports {vga_red_o[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_red_o[1]' has been applied to the port object 'vga_red_o[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_o[1]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_red_o[1]' has been applied to the port object 'vga_red_o[1]'.
set_property SLEW FAST [get_ports {vga_red_o[1]}]
set_property PACKAGE_PIN C5 [get_ports {vga_red_o[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_red_o[2]' has been applied to the port object 'vga_red_o[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_o[2]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_red_o[2]' has been applied to the port object 'vga_red_o[2]'.
set_property SLEW FAST [get_ports {vga_red_o[2]}]
set_property PACKAGE_PIN A4 [get_ports {vga_red_o[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_red_o[3]' has been applied to the port object 'vga_red_o[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red_o[3]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_red_o[3]' has been applied to the port object 'vga_red_o[3]'.
set_property SLEW FAST [get_ports {vga_red_o[3]}]
set_property PACKAGE_PIN B7 [get_ports {vga_blue_o[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_blue_o[0]' has been applied to the port object 'vga_blue_o[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_o[0]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_blue_o[0]' has been applied to the port object 'vga_blue_o[0]'.
set_property SLEW FAST [get_ports {vga_blue_o[0]}]
set_property PACKAGE_PIN C7 [get_ports {vga_blue_o[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_blue_o[1]' has been applied to the port object 'vga_blue_o[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_o[1]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_blue_o[1]' has been applied to the port object 'vga_blue_o[1]'.
set_property SLEW FAST [get_ports {vga_blue_o[1]}]
set_property PACKAGE_PIN D7 [get_ports {vga_blue_o[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_blue_o[2]' has been applied to the port object 'vga_blue_o[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_o[2]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_blue_o[2]' has been applied to the port object 'vga_blue_o[2]'.
set_property SLEW FAST [get_ports {vga_blue_o[2]}]
set_property PACKAGE_PIN D8 [get_ports {vga_blue_o[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_blue_o[3]' has been applied to the port object 'vga_blue_o[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blue_o[3]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_blue_o[3]' has been applied to the port object 'vga_blue_o[3]'.
set_property SLEW FAST [get_ports {vga_blue_o[3]}]
set_property PACKAGE_PIN C6 [get_ports {vga_green_o[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_green_o[0]' has been applied to the port object 'vga_green_o[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_o[0]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_green_o[0]' has been applied to the port object 'vga_green_o[0]'.
set_property SLEW FAST [get_ports {vga_green_o[0]}]
set_property PACKAGE_PIN A5 [get_ports {vga_green_o[1]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_green_o[1]' has been applied to the port object 'vga_green_o[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_o[1]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_green_o[1]' has been applied to the port object 'vga_green_o[1]'.
set_property SLEW FAST [get_ports {vga_green_o[1]}]
set_property PACKAGE_PIN B6 [get_ports {vga_green_o[2]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_green_o[2]' has been applied to the port object 'vga_green_o[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_o[2]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_green_o[2]' has been applied to the port object 'vga_green_o[2]'.
set_property SLEW FAST [get_ports {vga_green_o[2]}]
set_property PACKAGE_PIN A6 [get_ports {vga_green_o[3]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_green_o[3]' has been applied to the port object 'vga_green_o[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {vga_green_o[3]}]
# The conversion of 'SLEW' constraint on 'net' object 'vga_green_o[3]' has been applied to the port object 'vga_green_o[3]'.
set_property SLEW FAST [get_ports {vga_green_o[3]}]
set_property PACKAGE_PIN B11 [get_ports vga_hs_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_hs_o' has been applied to the port object 'vga_hs_o'.
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs_o]
# The conversion of 'SLEW' constraint on 'net' object 'vga_hs_o' has been applied to the port object 'vga_hs_o'.
set_property SLEW FAST [get_ports vga_hs_o]
set_property PACKAGE_PIN B12 [get_ports vga_vs_o]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vga_vs_o' has been applied to the port object 'vga_vs_o'.
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs_o]
# The conversion of 'SLEW' constraint on 'net' object 'vga_vs_o' has been applied to the port object 'vga_vs_o'.
set_property SLEW FAST [get_ports vga_vs_o]

# Incoming System Clock PERIOD Constraint

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

create_clock -name clk_i -period 10.000 [get_ports clk_i]

# Ignore Clock Domain Crossing signals
# These signals are coming from the 100MHz clock domain
# ant are not time-critical: RGB LED, Temperature, Accelerometer
# and Mouse Controller data, going to the 108Mhz clock domain, the VGA display controller

# Define a new TNM for a FROM - TO constraint

#get_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets clk_i]] -to [all_fanout -endpoints_only -flat -from [get_nets Inst_VGA/pxl_clk]]
