#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Wed Jun 15 16:25:36 CEST 2022
# SW Build 2700185 on Thu Oct 24 18:45:48 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xvlog --incr --relax -prj tb_sobelProc_vlog.prj"
xvlog --incr --relax -prj tb_sobelProc_vlog.prj 2>&1 | tee compile.log

echo "xvhdl --incr --relax -prj tb_sobelProc_vhdl.prj"
xvhdl --incr --relax -prj tb_sobelProc_vhdl.prj 2>&1 | tee -a compile.log

