#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed May 25 15:51:24 CEST 2022
# SW Build 2700185 on Thu Oct 24 18:45:48 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6737922d63e140f3b9b38e0796d63452 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_adrgenUnit_behav xil_defaultlib.tb_adrgenUnit xil_defaultlib.glbl -log elaborate.log"
xelab -wto 6737922d63e140f3b9b38e0796d63452 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_adrgenUnit_behav xil_defaultlib.tb_adrgenUnit xil_defaultlib.glbl -log elaborate.log

