# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /homes/abaghdad/SAR_info_ip/2021/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz.xci
# IP: The module: 'clk_wiz_vga_25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /homes/abaghdad/SAR_info_ip/2021/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga_25MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /homes/abaghdad/SAR_info_ip/2021/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /homes/abaghdad/SAR_info_ip/2021/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /homes/abaghdad/SAR_info_ip/2021/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz.xci
# IP: The module: 'clk_wiz_vga_25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /homes/abaghdad/SAR_info_ip/2021/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /homes/abaghdad/SAR_info_ip/2021/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /homes/abaghdad/SAR_info_ip/2021/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
