# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /homes/t21khieu/SAR/sobel/sobel.cache/wt [current_project]
set_property parent.project_path /homes/t21khieu/SAR/sobel/sobel.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /homes/t21khieu/SAR/sobel/sobel.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /homes/t21khieu/SAR/sobel/sources/DualPortRamGeneric.vhd
  /homes/t21khieu/SAR/sobel/sources/SinglePortROMFileInitGeneric.vhd
  /homes/t21khieu/SAR/sobel/sources/adrgenUnit.vhd
  /homes/t21khieu/SAR/sobel/sources/automate.vhd
  /homes/t21khieu/SAR/sobel/sources/gradientUnit.vhd
  /homes/t21khieu/SAR/sobel/sources/regUnit.vhd
  /homes/t21khieu/SAR/sobel/sources/pixedgeReg.vhd
  /homes/t21khieu/SAR/sobel/sobel.srcs/sources_1/imports/sources/operativeUnit.vhd
  /homes/t21khieu/SAR/sobel/sources/sobelProc.vhd
  /homes/t21khieu/SAR/sobel/sources/vga_nexys4_2regions.vhd
  /homes/t21khieu/SAR/sobel/sources/sobelSys.vhd
}
read_ip -quiet /homes/t21khieu/SAR/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz.xci
set_property used_in_implementation false [get_files -all /homes/t21khieu/SAR/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz_board.xdc]
set_property used_in_implementation false [get_files -all /homes/t21khieu/SAR/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz.xdc]
set_property used_in_implementation false [get_files -all /homes/t21khieu/SAR/sobel/sources/ip/clk_wiz_vga_25MHz/clk_wiz_vga_25MHz_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /homes/t21khieu/SAR/sobel/sources/Nexys4_Sobel.xdc
set_property used_in_implementation false [get_files /homes/t21khieu/SAR/sobel/sources/Nexys4_Sobel.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top sobelSys -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sobelSys.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sobelSys_utilization_synth.rpt -pb sobelSys_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
